### ISSUE TITLE
Funktioniert nicht mit aktueller Volkszähler-Version

### ISSUE THREAD

**Issue by melvinisken** [andig/vzvis#1]
Habe es gerade spaßeshalber mal getestet, und es funktioniert sowohl auf der lokalen VZ-Installation (checkout von gestern) als auch mit dem Demo-Server nicht mehr. Leider gibt es keine genaueren Fehler-Infos.. Ist allerdings ja auch recht alt der letzte Checkin.
Werde bei Gelegenheit versuchen, mir das noch mal genauer anzugucken..

**Comment by andig** [comment]
Fixed- was still using the meanwhile unsupported padded json requests.
